### ISSUE TITLE
[feature_request] Parameter to disable snapping back to 1.0 when armed

### ISSUE THREAD

**Issue by kmaxion** [gonuit/flutter-custom-refresh-indicator#11]
Hey, would it be possible to add a parameter to CustomRefreshIndicator to disable this line essentially ->
await _animationController.animateTo(1.0, duration: widget.armedToLoadingDuration);

For my use case, I want the Widgets dependent on the IndicatorController.value to stay the same until the onRefresh function completes.

**Comment by gonuit** [comment]
### Hi @kmaxion 👋🏻 ,
Thank you for opening this issue. Could you provide more details (indicator gif, more description)? Maybe this issue can be resolved in another way. For example, maybe you can clamp the controller value at 1.0 to prevent over-dragging.

**Comment by gonuit** [comment]
I am closing this issue due to lack of information.
