### ISSUE TITLE
[question]Is there a way to listen for the drag from bottom?

### ISSUE THREAD

**Issue by SeasonLeee** [gonuit/flutter-custom-refresh-indicator#12]
I believe we all have encountered scenario in developing a long list of data when we want to keep requesting more data from the server while user scroll at the end of the list...

I believe that's how we can scroll indefinitely on Twitter with their seemingly infinite data list.

So, this package provide us ways to pull down the list from the top to refresh the whole list, but from the api documentation, I don't see there's way to listen to the 'drag from bottom' event.

My question is, is it available to do that feature with this package?

Thanks in advance!

**Comment by gonuit** [comment]
### Hi @SeasonLeee 👋🏻!
This package provides `pull to refresh` logic and can be used as a replacement for the `RefreshIndicator` widget provided with the Flutter framework (material package).  If you want to implement an infinite scroll list, you should make use of other packages. For example, you can look at [infinite_scroll_pagination](https://pub.dev/packages/infinite_scroll_pagination) package.

Feel free, to reopen this issue and drop me a line if I can do anything else for you 😃.

**Comment by SeasonLeee** [comment]
Hey @gonuit Thanks for your response! It's really helpful! Especially that infinte_scroll_pagination package you mentioned!!!

Now I'm trying to combine your package and that package to make a list in our project... I will let you know if there's any compatibility issue, thanks again!😆
