### ISSUE TITLE
CheckMarkIdicatorExample - indicator visible without DecoratedBox behind list

### ISSUE THREAD

**Issue by skaletaPL** [gonuit/flutter-custom-refresh-indicator#13]
Hi,
First of all, thanks for sharing with that fancy code. 
When i use check mark indicator example without DecoratedBox on my ListView, the incidator is allways visible .
I saw that it can be hidden based on Indicator state, like in the plane indicator:
```dart
            return Stack(
              overflow: Overflow.clip,
              children: <Widget>[
                **if (_prevState != IndicatorState.idle)**
                  Container(
```

Is that the desired way to hide the CircularProgressIndicator for CheckMarkIdicator when using list without DecoratedBox?

To reproduce simply remove DecoratedBox from ExampleList

```dart
class ExampleList extends StatelessWidget {
  final Color backgroundColor;
  const ExampleList([this.backgroundColor = appBackgroundColor]);
  @override
  Widget build(BuildContext context) {
    return ListView.separated(
        itemBuilder: (BuildContext context, int index) => const Element(),
        itemCount: 4,
        separatorBuilder: (BuildContext context, int index) => const Divider(
          height: 0,
          color: Color(0xFFe2d6ce),
          thickness: 1,
        ),
      );
  }
}
```

**Comment by RicoLiu** [comment]
```js
controller.isIdle ? null : Text('Loading...')
```

**Comment by gonuit** [comment]
### Hi @skaletaPL 👋🏻 

If you want to hide some elements/widgets based on the indicator state. The best solution for this is to make some `ifs`.
Look at the @RicoLiu answer 😃 -  it doesn't matter what type of widget you are using.

If you have any other questions related to this topic, feel free to re-open this issue and ask them. 
Have a nice day! 😃
