### ISSUE TITLE
How to cancel pull to refresh?

### ISSUE THREAD

**Issue by RicoLiu** [gonuit/flutter-custom-refresh-indicator#16]
How to cancel pull to refresh when user is going up:
```
_controller.position.userScrollDirection == ScrollDirection.forward
```

**Comment by gonuit** [comment]
Hi @RicoLiu, 
This functionality will be added in the 1.0.0 release, which will be released in the upcoming days.

**Comment by gonuit** [comment]
@RicoLiu, release 1.0.0  is available on pub.dev. Now the `stopDrag` method is available in the IndicatorController class.
