### ISSUE TITLE
didStateChange never catch IndicatorState.hiding

### ISSUE THREAD

**Issue by ycherniavskyi** [gonuit/flutter-custom-refresh-indicator#19]
With current `didStateChange` implementaion next call `controller.didStateChange(from: IndicatorState.loading, to: IndicatorState.hiding)` and `{controller.didStateChange(to: IndicatorState.hiding)` never return `true`.

It seams then next [bloc](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/67438d415a94203b36c9aff592a0ce35ec6a1949/lib/src/custom_refresh_indicator.dart#L288):
```dart
    controller._setIndicatorState(IndicatorState.hiding);
    await _animationController.animateTo(0.0,
        duration: widget.loadingToIdleDuration);
```
execute `notifyListeners` of `IndicatorController` twice before `builder` of `AnimatedBuilder` called.

**Comment by ycherniavskyi** [comment]
Just for checking update mentioned bloc with next:
```dart
    controller._setIndicatorState(IndicatorState.hiding);
    await Future.delayed(Duration(milliseconds: 100));
    await _animationController.animateTo(0.0,
        duration: widget.loadingToIdleDuration);
```
and everything start work as expected - `didStateChange` start catching `IndicatorState.hiding`.

**Comment by gonuit** [comment]
Hi @ycherniavskyi , thank You for opening this issue.
Yeah, this is possible, it depends on the device its performance and a lot of other things, therefore to resolve this issue `didStateChange` will be removed in the `1.0.0.nullsafety.1` release together with the controller's `prevState`  property. Instead, there will be an `IndicatorStateHelper` class.

**Comment by gonuit** [comment]
Please check if the issue still persists for you on the release `1.0.0.nullsafety.1` with the `IndicatorStateHelper` class.

**Comment by ycherniavskyi** [comment]
Just check the new version and `IndicatorStateHelper` usage example within `check_mark_indicator.dart` and for sure it fixes the issue 👍.
