### ISSUE TITLE
Is there a way to show indicator in programmatically?

### ISSUE THREAD

**Issue by aitsuki** [gonuit/flutter-custom-refresh-indicator#22]
There is the similar question in stackoverflow: [How to show RefreshIndicator intially while waiting data from backend API?](https://stackoverflow.com/questions/44031454/how-to-show-refreshindicator-intially-while-waiting-data-from-backend-api)

**Comment by marcio-ota** [comment]
There is no CustomRefreshIndicatorState, was removed....

**Comment by gonuit** [comment]
Available since version `1.1.0`.
Take a look at the [example](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/master/example/lib/screens/programmatically_controlled_indicator_screen.dart).

**Comment by sinhpn92** [comment]
Did you solve @aitsuki ? I'm using bloc on my project. So using await to fetch api on refresh is not good.
