### ISSUE TITLE
Integration of custom-refresh-indicator and paginate_firestore

### ISSUE THREAD

**Issue by RoyalCoder88** [gonuit/flutter-custom-refresh-indicator#27]
Hi friends,

What I to integrate **[custom-refresh-indicator](https://pub.dev/packages/custom_refresh_indicator)** and **[paginate_firestore](https://pub.dev/packages/paginate_firestore)**, I think this feature will be very useful for a lot of devs, can somebody guide us on how to achieve this? Thanks in advance!

**Comment by gonuit** [comment]
Unfortunately, this is not the purpose of this package.
I want it to be as simple as possible (as it's already quite complicated 😅).
If you have a solution and think it might be helpful for others, don't hesitate to create and share your own package 💪🏻
