### ISSUE TITLE
Error with version 1.2.0 and flutter 2.10.5

### ISSUE THREAD

**Issue by veloso11** [gonuit/flutter-custom-refresh-indicator#32]
**On Xcode build:**
: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/src/custom_refresh_indicator.dart:209
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try calling using ?. instead.

**Comment by gonuit** [comment]
Thanks, @Jordan1122  for the pull request 💪🏻 
Changes are available on the pub.dev, since version `1.2.1`
```yaml
custom_refresh_indicator: ^1.2.1
```
