### ISSUE TITLE
Indicator always spinning

### ISSUE THREAD

**Issue by markzakharyan** [gonuit/flutter-custom-refresh-indicator#38]
Hi,

The indicator (checkmark indicator example) is constantly spinning, even when not actively refreshing.

Intended behavior is still the case when refresh occurs.

Here's a screenshot:
<img width="391" alt="Screenshot 2022-12-31 at 9 38 27 PM" src="https://user-images.githubusercontent.com/56100600/210162052-5a22c12b-0708-4fe8-a108-bf1303a017f3.png">

Any help would be appreciated :) thanks!

**Comment by gonuit** [comment]
Hi @markzakharyan 👋🏻
I'll take a look at it and let you know.

**Comment by sparkEEdev** [comment]
@markzakharyan Didnt investigate much, but changing alignment to **bottomCenter** [on this line](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/master/example/lib/indicators/check_mark_indicator.dart#L74) fixed it for me.

**Comment by gonuit** [comment]
### Hi @markzakharyan! 👋🏻

There was indeed a problem with the indicator. The problem has been resolved, and an improved checkmark indicator is available in the sample application in version [3.0.0-beta.2](https://pub.dev/packages/custom_refresh_indicator/versions/3.0.0-beta.2).

Source code can be found [HERE](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/release/v3.0.0/example/lib/indicators/check_mark_indicator.dart).
