### ISSUE TITLE
Refresh not showing when list has few items.

### ISSUE THREAD

**Issue by omarellakany** [gonuit/flutter-custom-refresh-indicator#39]
When there are a few items in the list, for example, 1 or 2 items, the list doesn't scroll, nor triggers a refresh.

**Comment by gonuit** [comment]
Are you sure that your list is scrollable? Make sure that the
`AlwaysScrollablePhysics` is set for the `ListView`'s `physics` argument.

niedz., 26 lut 2023, 12:32 użytkownik Omar Ellakany <
***@***.***> napisał:

**Comment by omarellakany** [comment]
Many thanks.
