### ISSUE TITLE
minimum duration setting

### ISSUE THREAD

**Issue by lukepighetti** [gonuit/flutter-custom-refresh-indicator#42]
I see that we have complete state duration which is nice, but what would be really nice is the ability to set a minimum refreshing duration. It just provides a more seamless experience while showing that actions are taking place

**Comment by gonuit** [comment]
Hi @lukepighetti 👋

I think that instead of adding another rarely used function to this package, we can take advantage of the `Future.wait`.

Take a look at this example:
```dart
onRefresh: () => Future.wait([
  refresh(),
  Future.delayed(Duration(milliseconds: 600)),
]),
```

What do you think about it? Let me know 😃
