### ISSUE TITLE
how can i support ListView reverse to load More data. look like IM app？

### ISSUE THREAD

**Issue by zeqinjie** [gonuit/flutter-custom-refresh-indicator#43]

**Comment by gonuit** [comment]
#### Hi @zeqinjie! 👋🏻 
You can take a look at the following [example](https://custom-refresh-indicator.klyta.it/#/horizontal) or this one with [fetch more functionality](https://custom-refresh-indicator.klyta.it/#/fetch-more).

The code for both of them is available in the example application. This should give you a good starting point :)
