### ISSUE TITLE
Is it possible to trigger refresh programmatically?

### ISSUE THREAD

**Issue by mohn93** [gonuit/flutter-custom-refresh-indicator#44]

**Comment by gonuit** [comment]
Yes, you can. Currently, it works in the same way as the built-in `RefreshIndicator` widget. You need to assign GlobalKey to the RefreshIndicator widget, and then you can call the method. There is also an example in this project. [You can check it out as a reference!](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/master/example/lib/screens/programmatically_controlled_indicator_screen.dart)

**Comment by Moyout** [comment]
> Yes, you can. Currently, it works in the same way as the built-in `RefreshIndicator` widget. You need to assign GlobalKey to the RefreshIndicator widget, and then you can call the method. There is also an example in this project. [You can check it out as a reference!](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/master/example/lib/screens/programmatically_controlled_indicator_screen.dart)
@gonuit 
Can only be used with 'Customs Refresh Indicator'?
Error occurred while using 'Customs Material Indicator'
