### ISSUE TITLE
Animate the indicator during pull

### ISSUE THREAD

**Issue by avishail** [gonuit/flutter-custom-refresh-indicator#46]
first, thanks for this package! the default RefreshIndicator gave me really hard time and didn't feel good while yours works and feels perfect.

Is it possible to make the custom refresh indicator to animate during pull? the same way the material RefreshIndicator behaves?

Thanks!

**Comment by gonuit** [comment]
#### Hi @avishail! 👋🏻 
Basically, you can do anything you want based on the `value` of the controller. You can take a look at some of the examples provided with this package, which should give you a good insight into what is possible 🚀 

If you have any other questions/concerns let me know, I will try to help :)
