### ISSUE TITLE
Untestable

### ISSUE THREAD

**Issue by KeithBacalso** [gonuit/flutter-custom-refresh-indicator#48]
I tried following this blog about testing using fling: https://guillaume.bernos.dev/properly-test-a-pull-to-refresh/ on how to test a RefreshIndicator which is also similar to this package, but the test fails. Can this package also be testable?

**Comment by gonuit** [comment]
Hi @KeithBacalso!

This package has already created unit tests. [You can check them for reference](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/master/test/src/custom_refresh_indicator_test.dart) 💡 

If that doesn't help, you can reopen the issue.

**Comment by KeithBacalso** [comment]
it is literally the same as the tutorial link I sent @gonuit

**Comment by KeithBacalso** [comment]
`CustomRefreshIndicator(
      builder: (context, child, controller) {
        return AnimatedBuilder(
          animation: controller,
          builder: (BuildContext context, _) => Stack(
            alignment: Alignment.topCenter,
            children: <Widget>[
              if (!controller.isIdle)
                Padding(
                  padding: const EdgeInsets.only(top: 16),
                  child: Lottie.asset(
                    ImageRes.loader,
                    package: 'maya_funds',
                    width: 90,
                  ),
                ),
              Transform.translate(
                offset: Offset(
                  0,
                  80 * controller.value,
                ),
                child: child,
              ),
            ],
          ),
        );
      },
      onRefresh: onRefresh,
      child: child,
    );`

**Comment by KeithBacalso** [comment]
```dart
CustomRefreshIndicator(
      builder: (context, child, controller) {
        return AnimatedBuilder(
          animation: controller,
          builder: (BuildContext context, _) => Stack(
            alignment: Alignment.topCenter,
            children: <Widget>[
              if (!controller.isIdle)
                Padding(
                  padding: const EdgeInsets.only(top: 16),
                  child: Lottie.asset(
                    ImageRes.loader,
                    package: 'maya_funds',
                    width: 90,
                  ),
                ),
              Transform.translate(
                offset: Offset(
                  0,
                  80 * controller.value,
                ),
                child: child,
              ),
            ],
          ),
        );
      },
      onRefresh: onRefresh,
      child: child,
    );
````
