### ISSUE TITLE
isnt offsetToArmed bugged? it seems to me that the controller.value is only 1 when i scrolled 100% past the offsetToArmed height

### ISSUE THREAD

**Issue by ember11498** [gonuit/flutter-custom-refresh-indicator#50]
So if I have an offsetToArmed of 50 per example, it seems to me the loading state is only triggered if the user scrolls down 100 pixels. I have been trying to understand but I believe it is a bug? i am using material 3 flutter.

**Comment by ember11498** [comment]
this might sound dumb but after days of trying to understand whats going wrong i found out it has nothing to do with the custom_refresh_indicator package. The error was because my listview had bouncing physics which messed up with the offsetToArmed making it only activate when the user doubled the extent i set in the customrefreshindicator property offsetToArmed

**Comment by gonuit** [comment]
Hi @ember11498 👋🏻, 
Interesting, can you provide more details? Maybe this is something that should be added to the readme file? 🤔
