### ISSUE TITLE
Question about the cancelling state - indicator container immediately closes on cancel

### ISSUE THREAD

**Issue by prostakov** [gonuit/flutter-custom-refresh-indicator#51]
I have issue with dragging on cancelling state.

This is example from [medium post](https://medium.com/flutter-community/how-to-create-your-own-pull-to-refresh-custom-refresh-indicator-widget-in-flutter-a3aa4e8bb42d):

```
class ExampleScreen extends StatefulWidget {
  const ExampleScreen({super.key});

  @override
  State<ExampleScreen> createState() => _ExampleScreenState();
}

class _ExampleScreenState extends State<ExampleScreen> {
  int _itemsCount = 10;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const ExampleAppBar(),
      body: CustomRefreshIndicator(
        onRefresh: () => Future.delayed(const Duration(seconds: 3)),
        trigger: IndicatorTrigger.leadingEdge,
        child: ExampleList(
          itemCount: _itemsCount,
          countElements: true,
        ),
        builder: (
          BuildContext context,
          Widget child,
          IndicatorController controller,
        ) {
          return Stack(
            alignment: Alignment.topCenter,
            children: <Widget>[
              if (!controller.isIdle)
                Positioned(
                  top: 35.0 * controller.value,
                  child: SizedBox(
                    height: 30,
                    width: 30,
                    child: CircularProgressIndicator(
                      value: !controller.isLoading ? controller.value.clamp(0.0, 1.0) : null,
                    ),
                  ),
                ),
              Transform.translate(
                offset: Offset(0, 100.0 * controller.value),
                child: child,
              ),
            ],
          );
        },
      ),
    );
  }
}
```

The problem is - that if I start slowly dragging down, and then I drag just one pixel to the top - and container closes immediately.

I wonder whether there maybe something I missed in configuration in order to address this...

**Comment by gonuit** [comment]
### Hi @prostakov 👋🏻
That's exactly how the built-in `RefreshIndicator` widget works, and that's how overscroll notifications work in Flutter.  

When the list is scrollable (has more content to scroll through), Flutter starts reporting scrolling as soon as the scrolling direction changes, even if a certain amount of overscroll was reported earlier. 

I will look into this issue and try to find a solution, but I don't know if this is possible based on scroll notifications.

**Comment by prostakov** [comment]
Ahhh, I see.

The lack of support on these things from the Flutter team is quite discouraging…

Thanks.

**Comment by gonuit** [comment]
@prostakov, possible workaround: https://github.com/gonuit/flutter-custom-refresh-indicator/issues/53#issuecomment-1877945455
