### ISSUE TITLE
IndicatorState may need an 'error' state.

### ISSUE THREAD

**Issue by CrazyWalk** [gonuit/flutter-custom-refresh-indicator#54]
When using onRefresh, if the future returns an exception, but the CustomRefreshIndicator only has a 'Complete' state, is there any way to display the refresh error?

**Comment by gonuit** [comment]
### Hi @CrazyWalk 👋🏻, 

The `complete` state does not tell you whether the callback was successful or not, but it does indicate that it completed. If you want to handle the error case, you need to implement this logic yourself. It should be relatively simple, just to give you an example.

1. Declare a property in the state object, such as `hasError`.
1. Implement the *onRefresh* callback with a try catch block to know whether the callback was successful or not.
    ```dart
    onRefresh: () async {
      try {
        await doSth();
        setState(() {
          hasError = false;
        });
      } on Exception catch (err, st) {
        setState(() {
          hasError = true;
        });
      }
    ```
2. Then, in a complete state, display another widget based on the `hasError` property (or any other).

**Comment by gonuit** [comment]
Hi @CrazyWalk,
I decided to add an example, you can check it **[HERE](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/f0200c919201032b20aeef75a3b030b23fc749a2/example/lib/indicators/check_mark_indicator.dart#L68)**
