### ISSUE TITLE
The listView is not displayed

### ISSUE THREAD

**Issue by StephentTom** [gonuit/flutter-custom-refresh-indicator#55]
CustomRefreshIndicator(
  onRefresh: onRefresh, 
  builder: (context, child, controller) {
    return Center(child: CupertinoActivityIndicator());
  },
  child: ListView.builder(
    itemBuilder: (_, index) => Text('Item $index'),
  ),
)

The listView is not displayed

**Comment by gonuit** [comment]
The ListView is provided as the second parameter of the builder method. It should be there placed in the widget tree.
