### ISSUE TITLE
[Question] finalizing animation

### ISSUE THREAD

**Issue by jccd1996** [gonuit/flutter-custom-refresh-indicator#58]
Hello!

Is it possible to change the duration of the finalizing state? I would like to add more time or add a smooth animation instead of closing the refresh indicator immediately. 

Thanks!

**Comment by jccd1996** [comment]
It seems that finalizeDuration is not working, I change the time duration in the indicatorFinalizeDuration (it is deprecated) and it's working.

**Comment by gonuit** [comment]
Hi @jccd1996 👋

Thank you for your insight, I will look into it 👀

**Comment by gonuit** [comment]
### Hi @jccd1996,

The problem has been resolved in version [3.1.1](https://pub.dev/packages/custom_refresh_indicator/versions/3.1.1). 

Thank you for reporting 💪🏻
