### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lvp305703574** [gonuit/flutter-custom-refresh-indicator#63]
Firstly, what I want to say is that this is a great library.
I encountered a problem while using it. When I adjusted the property "reverse" of the scrollbar to true, "Customs Material Indicator" changed to "pull up" mode. However, I still want to use "pull down" mode. Do you have such parameters?
thank you!
code Example:
SingleChildScrollView(
              reverse: true,
)

**Comment by gonuit** [comment]
### Hi @lvp305703574 👋

Thanks! Great to hear that!

It should be possible, please try the `trigger` parameter of the `CustomMaterialIndicator` and set its value to a trailing edge instead of leading (default).

```dart
trigger: IndicatorTrigger.trailingEdge,
```

Let me know if it helps!

**Comment by lvp305703574** [comment]
> ### Hi @lvp305703574 👋
> Thanks! Great to hear that!
> 
> It should be possible, please try the `trigger` parameter of the `CustomMaterialIndicator` and set its value to a trailing edge instead of leading (default).
> 
> ```dart
> trigger: IndicatorTrigger.trailingEdge,
> ```
> 
> Let me know if it helps!

Thanks a million! It can work normally!
