### ISSUE TITLE
[feature_request] Pull to refresh from bottom

### ISSUE THREAD

**Issue by aednlaxer** [gonuit/flutter-custom-refresh-indicator#8]
It would be nice to have an option to enable pull-to-refresh from bottom of the list and for both top and bottom

**Comment by gonuit** [comment]
Hi @aednlaxer,
It is possible to *enable* the bottom pull to refresh indicator. All you need to do is set the `reverse` argument on your scrollable widget like for example: `ListView` to `true`. Let me know if this is what you were looking for.
![example](https://user-images.githubusercontent.com/37882650/91694324-bbeba780-eb6c-11ea-8a92-025991facc4b.gif)

**Comment by aednlaxer** [comment]
I didn't know about the `reverse` argument, thanks. Although I'm looking for a bit different thing here. I have a `ListView` and I'd like to perform two different actions (and have two different indicators) when pulling down from the top and when pulling up from the bottom. Does library support this kind of behavior?

**Comment by kavienanj** [comment]
So you basically preparing to implement the lazy loading list view right?

**Comment by gonuit** [comment]
Hi @aednlaxer 👋🏻 , 
I close this issue as there is no more information. Feel free to reopen it if there is still a need for some action.

**Comment by gustavomaedo** [comment]
It is no longer working in Flutter 3

**Comment by AndreiMisiukevich** [comment]
Hey folks, what was the reason it's disabled in flutter 3?

**Comment by gonuit** [comment]
I'm on it 🕵🏻

**Comment by gonuit** [comment]
Hi @gustavomaedo,
What is the exact issue you are getting? I tested it on the latest version of Flutter (**3.3.2**) and it works fine for me. 🤔 
Maybe you are able to provide me a GIF/video, stack trace, or just give me more details about it 👀

**Comment by gonuit** [comment]
Oh, I see that this is not recognized correctly for the built-in `RefreshIndicator` widget, but the `CustomRefreshIndicator` widget provided by this package, still works. Is that correct?
If so, this issue is not related to this package code.

**Comment by aednlaxer** [comment]
I haven't tested this yet but it sounds fantastic! Thanks @gonuit! 🎉

**Comment by kimwest00** [comment]
It seems that `edge` parameter renaming to `trigger`
(just for share information :) )
