### ISSUE TITLE
Error When rebuilding child in CustomRefresher

### ISSUE THREAD

**Issue by Flucadetena** [gonuit/flutter-custom-refresh-indicator#9]
Hi, first of all, great package.

Im getting and error when I rebuild the child in `CustomRefresher`. I'm using a `StaggeredGridView`(or a `ListView`) inside the child, but I attach a controller to it as I need to listen to the scroll to know when it reaches the end and add more items to the list. To create an infinite scroll. 

The problem is that when I add those items this error appears:
```
═══════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for IndicatorController:
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

When the exception was thrown, this was the stack
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure>
package:flutter/…/widgets/binding.dart:783
#1      WidgetsBinding._handleBuildScheduled
package:flutter/…/widgets/binding.dart:806
#2      BuildOwner.scheduleBuildFor
package:flutter/…/widgets/framework.dart:2587
#3      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4311
#4      State.setState
package:flutter/…/widgets/framework.dart:1264
...
The IndicatorController sending notification was: Instance of 'IndicatorController'
════════════════════════════════════════════════════════════════════════════════
```

The app doesn't break, but it would be nice to solve it. 

Hope you can shine some light into it. Thanks! ;)

**Comment by gonuit** [comment]
### Hi @Flucadetena 👋🏻!

Thanks! I'm doing my best! ❤️ 

Did you solve the problem? It looks like you were setting the state while building the widget, but maybe there is something I can improve inside the library? 🤔

**Comment by Flucadetena** [comment]
Hi!! I don't remember very well. But something like that I think. I was rebuilding the whole widget when I added a new set of items to the `listView`. At the end, I created a Provider so that when new items are added only the list is rebuild.

Think It was something like that ;)

Anyway a solved it so 🥇 ajajjajaja. Keep up with the packge, is great. And if you need help don't hesitate to ask :)

**Comment by do4Mother** [comment]
hi @gonuit, I got the same problem here. is it possible to rebuild the widget instead of a custom refresh indicator? because I want to handle if there is no data then the user can still refresh the data. but if i handle rebuild in listview builder. the text error cannot move to the center.

**Comment by gonuit** [comment]
Hi @do4Mother, I think that your question is not related to the library itself. You are receiving this error because this is how the Flutter framework works. If you want to rebuild the widget from the build method, you can use for example:
```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
  setState(() {});
});
``` 
☝🏻  This will trigger the `setState` method right after the current frame/current build method.
